### ISSUE TITLE
Build nitrogen for windows

### ISSUE THREAD

**Issue by zkiiito** [LXJS/training-iot#53]
has anyone tried it yet?

**Comment by timfpark** [comment]
It should work - have a look at "Building on Windows" here: https://github.com/nitrogenjs/service

On Windows you need to install node-gyp and its dependences and OpenSSL before building.

Let me know if you've done that and are having issues.

**Comment by timfpark** [comment]
I just ran through it again and it all works on Windows.  I also added a Nitrogen device for a command line frame grabber to the getting started guide so you can perform that in Windows.   Have a look at issue https://github.com/LXJS/training-iot/issues/54 for more details...

**Comment by zkiiito** [comment]
after struggling with this for a while, here is my list to do it on windows7 x64:
I already had node and Python installed, installing openssl is also easy.

the microsoft things are a bit more different
- follow the things in the docs, so
  - install Microsoft Visual Studio C++ 2010 Express 
  - After this, uninstall any existing Visual C++ 2010 redistributable
  - install Windows 7 64-bit SDK
  - install Compiler update for the Windows SDK 7.1
- AND, you also need Microsoft Visual Studio 2010 Service Pack 1 - from here: http://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=23691

if you've installed all this, run
`npm install -g nitrogen-cli`
from the Windows 7 SDK7.1 Command prompt, because in the regular one it'll miss kernel32.dll

**Comment by timfpark** [comment]
Thank you - I added the recommendation to install the service pack to the documentation.
