### ISSUE TITLE
Controlling the webcam on windows

### ISSUE THREAD

**Issue by borgespires** [LXJS/training-iot#54]
I'm going through the  Nitrogen guide but when I reach the "Start ‘er up" part, I have no option has I'm working on windows, is there any solution?

**Comment by timfpark** [comment]
I am looking for a webcam command line tool that can emit a stream of the image data on stdout that I can build a Nitrogen device around on Windows.  Any ideas of a command line tool like this?

**Comment by timfpark** [comment]
Ok, I see something called CommandCam that should work.   I will write a device module for it - give me a few hours.

**Comment by borgespires** [comment]
Ok. Thanks :)

**Comment by timfpark** [comment]
Ok - done - I created a device around CommandCam and included it in the guide.  Can you refresh the page and try that guide again?  Also, you'll need to repull the camera project ('git pull origin master') as I added the CommandCamCamera to the app for you.   

Let me know if you run into any problems - happy to help - and thanks for reminding me that I needed to find a solution for this guide for Windows!   Close this issue out if you are successful and don't run into any issues.

**Comment by borgespires** [comment]
I started the camera device and connected to the service just fine.

6/19/2014 10:58:28: Camera: debug: session: created.
6/19/2014 10:58:29: Camera: debug: CommandManager::execute: emp
6/19/2014 10:58:29: Camera: info: commandManager: started.
6/19/2014 10:58:30: Camera: debug: session: socket.io connected

but when i send the snapshot command it fails with the following error:

``` javascript
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:998:11)
    at Process.ChildProcess._handle.onexit (child_process.js:789:34)
```

**Comment by timfpark** [comment]
Is CommandCam on your environment path?   It looks like it can't find that
command.

(Do 'echo %path%' and make sure that the directory with CommandCam is
listed.)

Tim

**Comment by borgespires** [comment]
You are rigth the path was wrong. 
But now I have the same error right after I try to start camera.js.
I tried deleting the device and run again but now it doesn't even create the device...

**Comment by timfpark** [comment]
Would you mind sending me the contents of camera.js?  I'll try to repo here.   Thanks and sorry that you are running into trouble.

**Comment by borgespires** [comment]
No problem and thanks for the help.
Maybe now I have to delete the executeQueue content has I keep receiving the request that failed. Is it possible?

Camera: info: CameraManager::executeQueue: command message satisfied: {...}

Here goes camera.js:

``` javascript
var config = require('./config')
  , nitrogen = require('nitrogen')
  , CommandCamCamera = require('commandcam')
  , ImageSnapCamera = require('nitrogen-imagesnap')
  , FSWebcamCamera = require('fswebcam')
  , CameraManager = require('nitrogen-camera');

var service = new nitrogen.Service(config);

var camera = new ImageSnapCamera({
    api_key: config.api_key,
    nickname: 'camera',
    name: "Camera"
});

service.connect(camera, function(err, session, camera) {
    if (err) { return console.log('failed to connect camera: ' + err); }

    new CameraManager(camera).start(session, function(err, message) {
        if (err) return session.log.error(JSON.stringify(err));
    });
});
```

**Comment by timfpark** [comment]
Ah, I see the problem.   Change ImageSnapCamera -> CommandCamCamera on this line:

var camera = new ImageSnapCamera({
    api_key: config.api_key,
    nickname: 'camera',
    name: "Camera"
});

By default, the sample is written for folks on the Mac and for Windows we need to change it.

**Comment by borgespires** [comment]
Yep, it worked, it responded the pending request, thanks. But now has I deleted the device a new one is not created on the nitrogen web admin page. How can I do that?

**Comment by timfpark** [comment]
Hmmm.  I need to make reclaiming a device easier like this.  Just to make sure I understand the scenario, you:
1. Deleted it in web admin.
2. Restarted it.

If so, what has happened is that Nitrogen has deleted the permissions from your user account - I should print a message with a way to reclaim the device after you have done that but I see that I am not. :)

So, let's do this:
1. Stop the camera application
2. Delete the api.nitrogen.io_443 directory
3. Restart the camera application

That will create a new camera device in Nitrogen and automatically associate it with your account.

**Comment by borgespires** [comment]
It is working fine now. Thanks and sorry for bothering you.

**Comment by timfpark** [comment]
No - this has been super helpful in finding issues.  Thanks for putting up with all of the "growing pains"

**Comment by borgespires** [comment]
Happy to help. Thanks.
