### ISSUE TITLE
Trouble with Raspberry Pi

### ISSUE THREAD

**Issue by hyprstack** [LXJS/training-iot#56]
Hi,

When following the Raspberry Setup, I run into a problem. As I have mentioned in my previous issue, I am new to this so some things are not so linear for me and I have found following some parts of this particular tutorial (i2c) challenging. 

After following these instructions:
`$ sudo vi /etc/modules`
`_Add these two lines_`

`i2c-bcm2708` 
`i2c-dev`

I exited _vi_ by typing `:wq`. I imagine this is correct? 

When I reach the part where I am supposed to type:
`$ sudo vi /etc/modprobe.d/raspi-blacklist.conf` there is nothing in this file. So how am I supposed to `Comment out blacklist i2c-bcm2708` ? 

If I type  `#blacklist i2c-bcm2708` into the new file just opened above, when I try to save it and exit _vi_, I get an error `E212: Can't open file for writing`.

Thanks

**Comment by timfpark** [comment]
Hi Mario,

Are you using the image that you downloaded from the Nitrogen web admin?   If so, this step is easy - I have already done it for you! :)

**Comment by hyprstack** [comment]
Thanks Tim. I've downloaded the image ;)
