### ISSUE TITLE
broken code in solutions/2

### ISSUE THREAD

**Issue by ricardobeat** [LXJS/training-iot#59]
the call to `bmp085.measure` takes only a callback, and returns an array containing two `nitrogen.Message` instances ready to be sent, but the sample code passes it the session and repeats the `.measure` method contents.

Working code:

```
bmp085.measure(function(err, messages) {
    nitrogen.Message.sendMany(session, messages)
    console.log('Messages sent')
})
```

**Comment by timfpark** [comment]
Thank you!  Pushed fix to training.
