### ISSUE TITLE
Suggestions for the next iot workshop

### ISSUE THREAD

**Issue by alextreppass** [LXJS/training-iot#60]
1) Run the internetofthings access point in wireless repeater mode

i.e. your netgear router should offer a wireless connection and DHCP as necessary, but should pass-off traffic to the conference host wifi.

No idea if netgear firmware allows you to do this by default, however using something like [DD-WRT](http://www.dd-wrt.com/wiki/index.php/Repeater) would let you.

2) On the Raspberry Pi device image(s), put the package.json in the folder just above the the training excercises, and npm install the required things. Running node device.js in the exercises will then traverse up to find the shared node_modules folder. This would cut down on a lot of the npm install / native gyp time.

**Comment by timfpark** [comment]
Thanks Alex!  I'll definitely bring better gear for the next event.

I spent all night (literally) doing #2 - so for today's session that will be the case.

Sorry again that there were so many problems yesterday and thanks for your feedback.  If you want to drop by at the beginning of the workshop today, I'd love to give you a Raspberry Pi Prototyping Plate.

**Comment by alextreppass** [comment]
Hey thanks. Arduinos and Pis are new to me, so playing with them in the nodebots and the iot workshop was fun
